#!/usr/bin/env bash

#DO NOT EDIT THIS FILE
# for changes to dev box configuration, simply update the my_dev_box role in the
# roles/ subdirectory of this current path

cd "$(dirname "$0")"

/usr/local/bin/ansible-playbook ./bs_playbook.yaml
